# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_config: default
dataset_prompt_column: problem
system_prompt: "You are a helpful AI Assistant, designed to provided well-reasoned and detailed responses. You FIRST think about the reasoning process step by step and then provide the user with the answer. Please enclose your final answer in the box: \\boxed{Your Answer}. Please stop generation immediately after outputing the box."

# GRPO trainer config
bf16: true
beta: 0.005 # kl penalty
use_vllm: true
do_eval: false
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: every_save
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 3072
max_steps: -1
num_generations: 7
num_train_epochs: 1
num_iterations: 1
output_dir: data/Qwen2.5-Intuitor-3B
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
reward_funcs:
- accuracy 
reward_weights:
- 0.0 # Include accuracy reward for monitorying purpose, remove reward_funcs and reward_weights for open-generation RL
save_strategy: "steps"
save_total_limit: 6
save_steps: 10
seed: 7
warmup_ratio: 0.1